# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('information', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
