# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], max_length=20)),
                ('club_secretary', models.CharField(max_length=20)),
                ('club_joint_secretary', models.CharField(max_length=20)),
                ('club_info', models.TextField()),
                ('club_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
    ]
