# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('ArtClub', 'ARTCLUB'), ('DanceClub', 'DANCECLUB'), ('MusicClub', 'MUSICCLUB'), ('CodingClub', 'CODINGCLUB')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('information', models.TextField()),
                ('post_time', models.DateTimeField(default=datetime.datetime(2017, 9, 9, 7, 22, 3, 788988, tzinfo=utc))),
            ],
        ),
    ]
