# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20171002_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], max_length=20)),
                ('club_secretary', models.CharField(max_length=20)),
                ('club_joint_secretary', models.CharField(max_length=20)),
                ('club_info', models.TextField()),
                ('club_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Club')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.CharField(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 15, 8, 435806, tzinfo=utc)),
        ),
    ]
