# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20171002_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 16, 35, 798686, tzinfo=utc)),
        ),
    ]
