# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20171002_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], on_delete=django.db.models.deletion.CASCADE, to='basic.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 23, 45, 547475, tzinfo=utc)),
        ),
    ]
