# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20171002_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 18, 3, 6, 681123, tzinfo=utc)),
        ),
    ]
