# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20171003_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.CharField(choices=[('ArtClub', 'ART CLUB'), ('DanceClub', 'DANCE CLUB'), ('MusicClub', 'MUSIC CLUB'), ('CodingClub', 'CODING CLUB'), ('GamingClub', 'GAMING CLUB'), ('PhotographyClub', 'PHOTOGRAPHY CLUB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 21, 41, 24, 467718, tzinfo=utc)),
        ),
    ]
