# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20171003_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 15, 32, 43, 446655, tzinfo=utc)),
        ),
    ]
