# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_auto_20171004_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 10, 26, 40, 557125, tzinfo=utc)),
        ),
    ]
