# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_auto_20171005_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('information', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 9, 46, 52, 942019, tzinfo=utc)),
        ),
    ]
