# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_auto_20171006_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 9, 48, 17, 287726, tzinfo=utc)),
        ),
    ]
